### ISSUE TITLE
python 2.6: ginnoptimizer.py will not run on 

### ISSUE THREAD

**Issue by georgepatterson** [deimosfr/galera_innoptimizer#6]
While I appreciate that python 2.6 is getting on a bit but it's standard for Centos/RHEL 6.x..

I found that the following error occurs:

```
-> optimizing {table_name} (16.0KiB) in progress..........
Traceback (most recent call last):
  File "ginnoptimizer.py", line 512, in <module>
    main()
  File "ginnoptimizer.py", line 509, in main
    args()
  File "ginnoptimizer.py", line 500, in args
    optimize_rsu(database, tables_list, fcpmax)
  File "ginnoptimizer.py", line 252, in optimize_rsu
    launch_sql_queries(row[0], row[1])
  File "ginnoptimizer.py", line 231, in launch_sql_queries
    print_formatted_results(start_time, size)
  File "ginnoptimizer.py", line 201, in print_formatted_results
    time_spent = (datetime.now() - optimize_start).total_seconds()
AttributeError: 'datetime.timedelta' object has no attribute 'total_seconds'
```

I added some code which I found around the web to address the missing total_seconds as well as subsequent errors. 
such as

```
-        print_color('ok', ' (' + '{:.1f}'.format(time_spent) + 's; ' + sizeof_fmt(table_size/time_s                                         pent) + '/s)')
+        print_color('ok', ' (' + '{0:.1f}'.format(time_spent) + 's; ') # + sizeof_fmt(table_size/time_spent) + '/s)')

Note the zero in the format string.

Let me know how I should submit this patch (Assuming that it would be helpful)
```

**Comment by deimosfr** [comment]
Hi,

Sorry but I don't have the time to backport it to Python 2.6. I would be happy if you make a PR.

Thanks
